services:
  app:
    image: redis:latest
    restart: always
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
  commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "6333:8081"
  mlworker:
    container_name: mlworker
    hostname: mlworker
    image: mlworker
    restart: always
    environment:
      - REDIS_URL=redis://redis:6379
      - MODEL_PATH=https://mymc.sfo2.digitaloceanspaces.com/models/2024-07-19model.pth
